[Library updated] Authors Removed
utopia-php/abuse pull request #34
Opened 2022-10-22 03:04 UTC by Tiansing

All authors mentioned were successfully removed!

2022-10-27 07:14 UTC, Meldiron requested changes
One tiny comment 🤏 I can mark as approved once resolved.

Also, looks like you done changes to composer lockfile. Can we revert those? This file is auto-generated so authors there done need to be touched - it will get re-added anyway.

2022-10-27 07:14 UTC, Meldiron commented on tests/Abuse/AbuseTest.php
> - * @author Eldad Fux <eldad@appwrite.io>
Let's remove the whole comment blocks, please.

2022-10-27 10:12 UTC, Tiansing commented
> 

@Meldiron Done resolving this issue thanks

2022-10-31 16:28 UTC, PineappleIOnic commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-11-07 18:04 UTC, stnguyen90 submitted a review, later dismissed
Great PR! 🤯 We left some comments during the review, please check them out.

2022-11-07 18:04 UTC, stnguyen90 commented on composer.lock
> -            "authors": [
There's no need to remove the authors from this file as they're automatically generated.

2022-11-09 07:46 UTC, Tiansing commented on composer.lock
> -            "authors": [
@stnguyen90 noted that!

2022-11-09 08:37 UTC, stnguyen90 commented on composer.lock
> -            "authors": [
@Tiansing please make sure to revert those changes of yours and resolve any merge conflicts if there are any.

2023-01-27 14:47 UTC, christyjacob4 approved these changes

2023-01-27 14:48 UTC, merged

2023-01-27 14:48 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

2023-02-04 02:38 UTC, Tiansing commented
> https://github.com/orgs/appwrite/invitation

Hi @christyjacob4, I can't access the URL you've provided for me to accept the github org invitation. Please send me an updated invitation link for GitHub appwrite org, I would love to join in your community